version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: gsoc_colab_postgres07
      POSTGRES_PASSWORD: gsoc_colab_postgres07
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
