import Headers from "@/components/landingPage/Headers";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/lib/reactQuery-provider";
import SessionWrapper from "@/lib/SessionWrapper";
import { Toaster } from "@/components/ui/sonner";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
         <SessionWrapper >
            <Provider>
              <Toaster />
              <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
              >
                
                <Headers />
                {children}
              </ThemeProvider>
            </Provider>
         </SessionWrapper>       
      </body>
    </html>
  );
}
